CREATE EXTERNAL TABLE irae__gpt4_raw
(
    filename	                            string,
    dsa_is_present	                        boolean,
    dsa_mentioned	                        boolean,
    dsa_history	                            boolean,
    dsa_present	                            string,
    infection_is_present	                boolean,
    infection_mentioned	                    boolean,
    infection_history	                    boolean,
    infection_present	                    string,
    viral_infection_is_present	            boolean,
    viral_infection_mentioned	            boolean,
    viral_infection_history	                boolean,
    viral_infection_present	                string,
    bacterial_infection_is_present	        boolean,
    bacterial_infection_mentioned	        boolean,
    bacterial_infection_history	            boolean,
    bacterial_infection_present	            string,
    fungal_infection_is_present	            boolean,
    fungal_infection_mentioned	            boolean,
    fungal_infection_history	            boolean,
    fungal_infection_present	            string,
    graft_rejection_is_present	            boolean,
    graft_rejection_mentioned	            boolean,
    graft_rejection_history	                boolean,
    graft_rejection_present	                string,
    graft_failure_is_present	            boolean,
    graft_failure_mentioned	                boolean,
    graft_failure_history	                boolean,
    graft_failure_present	                string,
    ptld_is_present	                        boolean,
    ptld_mentioned	                        boolean,
    ptld_history	                        boolean,
    ptld_present	                        string,
    cancer_is_present	                    boolean,
    cancer_mentioned	                    boolean,
    cancer_history	                        boolean,
    cancer_present	                        string,
    donor_transplant_date_mentioned	        boolean,
    donor_transplant_date	                date,
    donor_type_mentioned	                boolean,
    donor_type	                            string,
    donor_relationship_mentioned	        boolean,
    donor_relationship	                    string,
    donor_hla_match_quality_mentioned	    boolean,
    donor_hla_match_quality	                string,
    donor_hla_mismatch_count_mentioned	    boolean,
    donor_hla_mismatch_count	            string,
    rx_therapeutic_mentioned	            boolean,
    rx_therapeutic_therapeutic	            string,
    rx_therapeutic_subtherapeutic	        string,
    rx_therapeutic_supratherapeutic	        string,
    rx_compliance_mentioned	                boolean,
    rx_compliance_compliant	                string,
    rx_compliance_partial	                string,
    rx_compliance_noncompliant	            string,
    error_found                             boolean
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
STORED AS TEXTFILE
LOCATION 's3://cumulus-analytics/andy/irae/gpt4/July17/'
TBLPROPERTIES ("skip.header.line.count"="1");

